INSERT INTO hobby (NAME, DESCRIPTION)  VALUES ('3D-udskrivning','https://en.wikipedia.org/wiki/3D_printing');
INSERT INTO hobby (NAME, DESCRIPTION)  VALUES ('Akrobatik','https://en.wikipedia.org/wiki/Acrobatics');
INSERT INTO hobby (NAME, DESCRIPTION)  VALUES ('Skuespil','https://en.wikipedia.org/wiki/Acting');
INSERT INTO hobby (NAME, DESCRIPTION)  VALUES ('Amatørradio','https://en.wikipedia.org/wiki/Amateur_radio');
INSERT INTO hobby (NAME, DESCRIPTION)  VALUES ('Animation','https://en.wikipedia.org/wiki/Animation');
INSERT INTO hobby (NAME, DESCRIPTION)  VALUES ('Aquascaping','https://en.wikipedia.org/wiki/Aquascaping');
INSERT INTO hobby (NAME, DESCRIPTION)  VALUES ('Astrologi','https://en.wikipedia.org/wiki/Astrology');
INSERT INTO hobby (NAME, DESCRIPTION)  VALUES ('Bagning','https://en.wikipedia.org/wiki/Baking');
INSERT INTO hobby (NAME, DESCRIPTION)  VALUES ('Baton snurrer','https://en.wikipedia.org/wiki/Baton_twirling');
INSERT INTO hobby (NAME, DESCRIPTION)  VALUES ('Blogging','https://en.wikipedia.org/wiki/Blogging');
INSERT INTO hobby (NAME, DESCRIPTION)  VALUES ('Brætspil','https://en.wikipedia.org/wiki/Board_game');
INSERT INTO hobby (NAME, DESCRIPTION)  VALUES ('Bogdiskussionsklub','https://en.wikipedia.org/wiki/Book_discussion_club');
INSERT INTO hobby (NAME, DESCRIPTION)  VALUES ('Gendannelse af bøger','https://en.wikipedia.org/wiki/Book_restoration');
INSERT INTO hobby (NAME, DESCRIPTION)  VALUES ('Bowling','https://en.wikipedia.org/wiki/Bowling');
INSERT INTO hobby (NAME, DESCRIPTION)  VALUES ('Brasiliansk jiu-jitsu','https://en.wikipedia.org/wiki/Brazilian_jiu-jitsu');
INSERT INTO hobby (NAME, DESCRIPTION)  VALUES ('Brødfremstilling','https://en.wikipedia.org/wiki/Breadmaking');
INSERT INTO hobby (NAME, DESCRIPTION)  VALUES ('Bygning','https://en.wikipedia.org/wiki/Building');
INSERT INTO hobby (NAME, DESCRIPTION)  VALUES ('Bullet Journal','https://en.wikipedia.org/wiki/Bullet_Journal');
INSERT INTO hobby (NAME, DESCRIPTION)  VALUES ('Cabaret','https://en.wikipedia.org/wiki/Cabaret');
INSERT INTO hobby (NAME, DESCRIPTION)  VALUES ('Kalligrafi','https://en.wikipedia.org/wiki/Calligraphy');
INSERT INTO hobby (NAME, DESCRIPTION)  VALUES ('Lysfremstilling','https://en.wikipedia.org/wiki/Candle_making');
INSERT INTO hobby (NAME, DESCRIPTION)  VALUES ('Slikfremstilling','https://en.wikipedia.org/wiki/Candy_making');
INSERT INTO hobby (NAME, DESCRIPTION)  VALUES ('Bil','https://en.wikipedia.org/wiki/Car');
INSERT INTO hobby (NAME, DESCRIPTION)  VALUES ('Kortspil','https://en.wikipedia.org/wiki/Card_games');
INSERT INTO hobby (NAME, DESCRIPTION)  VALUES ('Cardistry','https://en.wikipedia.org/wiki/Cardistry');
INSERT INTO hobby (NAME, DESCRIPTION)  VALUES ('Ostemagning','https://en.wikipedia.org/wiki/Cheesemaking');
INSERT INTO hobby (NAME, DESCRIPTION)  VALUES ('Rengøring','https://en.wikipedia.org/wiki/Cleaning');
INSERT INTO hobby (NAME, DESCRIPTION)  VALUES ('Tøj','https://en.wikipedia.org/wiki/Clothing');
INSERT INTO hobby (NAME, DESCRIPTION)  VALUES ('Hjemmelavet kaffe','https://en.wikipedia.org/wiki/Home_roasting_coffee');
INSERT INTO hobby (NAME, DESCRIPTION)  VALUES ('Indsamling','https://en.wikipedia.org/wiki/Collecting');
INSERT INTO hobby (NAME, DESCRIPTION)  VALUES ('Malebog','https://en.wikipedia.org/wiki/Coloring_book');
INSERT INTO hobby (NAME, DESCRIPTION)  VALUES ('Computer programmering','https://en.wikipedia.org/wiki/Computer_programming');
INSERT INTO hobby (NAME, DESCRIPTION)  VALUES ('Konfekture','https://en.wikipedia.org/wiki/Confectionery');
INSERT INTO hobby (NAME, DESCRIPTION)  VALUES ('Madlavning','https://en.wikipedia.org/wiki/Cooking');
INSERT INTO hobby (NAME, DESCRIPTION)  VALUES ('Cosplaying','https://en.wikipedia.org/wiki/Cosplaying');
INSERT INTO hobby (NAME, DESCRIPTION)  VALUES ('Kuponering','https://en.wikipedia.org/wiki/Couponing');